project_id = "jubqccofwpmflhsxtiry"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.run-analysis]
verify_jwt = true

[functions.create-test-users]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
